version: '3.8'

services:
  mydb:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      - MYSQL_DATABASE=food_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    volumes:
      - ./volumes/db:/var/lib/mysql

  web:
    build: .
    container_name: controlfood
    ports:
      - "5001:5000"
    volumes: 
        - ".:/pycode"
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_DATABASE=food_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - mydb

